spring.application.name=easypay
spring.datasource.url=jdbc:mysql://localhost:3306/EasyRoll?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

# JWT Settings
# A secure, Base64-encoded secret key for signing JWTs.
bezkoder.app.jwtSecret=VGhpc0lzQVNlY3JldEtleUZvckp3dEF1dGhlbnRpY2F0aW9uSW5UaGVFYXN5Um9sbEFwcGxpY2F0aW9u
bezkoder.app.jwtExpirationMs=86400000
